### DISCUSSION TITLE
Gridexplorer CSS snippets

### DISCUSSION THREAD

**Discussion by Devon22** [Devon22/obsidian-gridexplorer#19] [Show and tell]
![2025-04-06 154546](https://github.com/user-attachments/assets/453dcf00-a2ab-460f-8c68-446376d1d76e)

```
.ge-grid-item {
  background: ivory;
  border-top:10px solid gold;
  font-size: 16px;
}

.ge-title {
  height: 2.8em;
  white-space: pre-wrap;
  font-size: 14px;
  color: navy;
  font-weight: bold;
}
```

source: [Jazzと読書の日々](https://wineroses.hatenablog.com/entry/2025/03/12/131227)

**Comment by Moyf** [comment]
![Snipaste_2025-06-25_16-22-41](https://github.com/user-attachments/assets/98918d50-8014-400d-a4cf-b98f656aaedc)

Special style for folder-note:

```css
.ge-grid-item.ge-foldernote {
    /* 复用文件夹的 */
    border: 2px solid var(--background-modifier-border) !important;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);

    /* 手动添加左侧高亮 */
    /* 先取消 padding */
    padding: 0px !important;

    /* 再在子级里重新加回去 */
    .ge-content-area {
        padding: 10px;
    }

    /* 左侧黄条 */
    &::before {
        content: " ";
        width: 1em;    
        background-color: #ffdb0e; /* 第二层边框 */
        /* z-index: -1; */
    }
}

```
